AbstractOdeSolver.o : AbstractOdeSolver.cpp AbstractOdeSolver.hpp
	g++ -c -g AbstractOdeSolver.cpp

ForwardEulerSolver : AbstractOdeSolver.hpp ForwardEulerSolver.cpp 
	g++ -o ForwardEulerSolver ForwardEulerSolver.cpp

RungeKuttaSolver : AbstractOdeSolver.hpp RungeKuttaSolver.cpp 
	g++ -o RungeKuttaSolver RungeKuttaSolver.cpp
